let lieblingsBuch = "Der Herr der Ringe";
let anzahlGeschwister = 2;
let hatFuehrerschein = true;
let momentaneStimmung = null;
let naechsteReiseziel;
let lieblingsFarbe = "Blau";
let wohnflaeche = 85;
let magKaffee = true;
let aktuellesProjekt = null;
let letztesAbendessen;
let geburtstadt = "Berlin";
let kaffeetassenProTag = 3;
let istVegetarier = false;
let zukunftsWunsch = null;
let lieblingsSportart;
let lieblingsFilm = "Der Herr der Ringe: Die Gefährten";
let hoeheInCm = 178;
let hatHaustier = true;
let mittagessenIdee = null;
let lieblingsMusikband;